apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-ibmc-storage-<username>
  namespace: <username>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-nvme-vg
  resources:
    requests:
      storage: 250Gi
