apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-py3-10-<username>
  namespace: <username>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-nvme-vg
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-py3-11-<username>
  namespace: <username>
spec:
  resources:
    requests:
      storage: 250Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-nvme-vg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-py3-12-<username>
  namespace: <username>
spec:
  resources:
    requests:
      storage: 250Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-nvme-vg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-py3-13-<username>
  namespace: <username>
spec:
  resources:
    requests:
      storage: 250Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-nvme-vg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-py3-14-<username>
  namespace: <username>
spec:
  resources:
    requests:
      storage: 250Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-nvme-vg