apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: runtime-request-timeout
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  kubeletConfig:
    runtimeRequestTimeout: "10m"
