apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: nvidia-gpu-operator
data:
  config.json: |
    {
      "periodicUpdateInterval": 300,
      "configList": [
        {
          "resourceName": "rdma_shared_device_a",
          "rdmaHcaMax": 100,
          "selectors": {
            "vendors": ["15b3"],
            "deviceIDs": ["101e"]
          }
        }
      ]
    }
