apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: <username>
spec:
  hard:
    # MIG slices
    requests.nvidia.com/mig-1g.18gb: "1"
    requests.nvidia.com/mig-2g.35gb: "1"
    requests.nvidia.com/mig-1g.10gb: "1"
    limits.nvidia.com/mig-1g.10gb: "1"
    requests.nvidia.com/mig-2g.20gb: "1"
    limits.nvidia.com/mig-2g.20gb: "1"

    # Full GPUs
    requests.nvidia.com/gpu: "0"

    # CPU and memory
    requests.cpu: "16"
    requests.memory: 128Gi
    limits.cpu: "64"
    limits.memory: 512Gi

    # Storage
    requests.storage: 300Gi
    persistentvolumeclaims: "5"